name: Calculator
version: 0.2.2.1
description: Please see the README on GitHub at <https://github.com/ddxtanx/calculator#readme>
author: Garrett Credi
copyright: 2020 Garrett Credi
github: ddxtanx/calculator
dependencies:
  base: "<=4.13.0.0"
library:
  exposed: True
  source-dirs:
    src

executable:
  source-dirs:
    - app
    - src
  main:
    Main.hs

tests:
  calculator-tests:
    main: Main.hs
    source-dirs: test
    dependencies: 
      - Calculator
      - tasty
      - tasty-hunit
      - tasty-quickcheck

    
  
  
    
