name: Haskulator
version: 1.0.0.0
description: Please see the README on GitHub at <https://github.com/ddxtanx/haskulator#readme>
author: Garrett Credi
copyright: 2020 Garrett Credi
github: ddxtanx/haskulator
dependencies:
  base: "<=4.13.0.0"
source-dirs:
    src
library:
  exposed: True
  

executable:
  source-dirs:
    - app
  main:
    Main.hs

tests:
  calculator-tests:
    main: Main.hs
    source-dirs: 
      - test
    dependencies: 
      - tasty
      - tasty-hunit
      - tasty-quickcheck

    
  
  
    
